# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-30 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
